export const paranaCities = [
  "Curitiba",
  "Londrina",
  "Maringá",
  "Ponta Grossa",
  "Cascavel",
  "São José dos Pinhais",
  "Foz do Iguaçu",
  "Colombo",
  "Guarapuava",
  "Paranaguá",
  "Araucária",
  "Toledo",
  "Apucarana",
  "Pinhais",
  "Campo Largo",
  "Arapongas",
  "Almirante Tamandaré",
  "Umuarama",
  "Cambé",
  "Fazenda Rio Grande",
  "Piraquara",
  "Sarandi",
  "Francisco Beltrão",
  "Castro",
  "Telêmaco Borba",
  "Cianorte",
  "Rolândia",
  "Irati",
  "União da Vitória",
  "Santo Antônio da Platina",
];
